[package]
name = "sir_mark"
version = "0.1.1"
edition = "2018"

[lib]
path = "./sir_mark.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sir = { path = "../sir/" }
