[package]
name = "sir"
version = "0.1.0"
edition = "2018"

[lib]
path = "./sir.rs"

[dependencies]
sir_macro = { path = "../sir_macro", version = "0.1.0" }
mopa = "0.2"
#eztrace = "*"

#field-offset = "0.3"
